# Setup
title:        Clive Wan
tagline:      Jack of all trades, Cornell alum, UMass Amherst alum, Quincy College alum, engineer, Toastmaster, speechwriter, definitely one of the smartest and most well-rounded people out there.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Clive Wan
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
